// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhrnshvgoyzhpbtjgoof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocm5zaHZnb3l6aHBidGpnb29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTUwMzksImV4cCI6MjA3MjIzMTAzOX0.No5DCEPw_yrRUhbwj71jpjBciq41auB_y2h_wRlKEpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});