name: Deploy to VPS (root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            cd /var/www/Mysqrfit24

            echo "📥 Pull latest code"
            git pull origin main

            
            echo "🎨 Frontend build"
            cd frontend
            npm install
            npm run build

            echo "📦 Backend dependencies"
            cd ../backend
            npm install
            pm2 restart mysqft-backend


            echo "♻ Reload nginx"
            systemctl reload nginx
          EOF
